### ISSUE TITLE
HTML Changed for website

### ISSUE THREAD

**Issue by a8hay** [pushker-git/strivers-sde-sheet-progress-tracker#2]
Markup has been changed for site, will have to account for that.
![image](https://user-images.githubusercontent.com/46368902/149545240-65c3ad2b-d6e7-4b40-a90f-5affbb8157e5.png)

**Comment by pushker-git** [comment]
Adopted the new html page design. Update your chrome extension. 
https://github.com/pushker-git/strivers-sde-sheet-progress-tracker/releases/tag/v2.0.0
